// This is the actual in-game catalogue, not a candidate pool. A name belongs
// here only when it is reasonable to expect recognition in a mixed Indian
// room through movies, television, news, sport, music, or social media.

export const CELEBRITY_NAMES = [
  'A. P. J. Abdul Kalam',
  'A. R. Rahman',
  'Aamir Khan',
  'AB de Villiers',
  'Abhinav Bindra',
  'Abhishek Bachchan',
  'Abhishek Upmanyu',
  'Adam Gilchrist',
  'Adele',
  'Aditya Roy Kapur',
  'Adolf Hitler',
  'Aishwarya Rai Bachchan',
  'Ajay Devgn',
  'Ajay Jadeja',
  'Ajinkya Rahane',
  'Ajith Kumar',
  'Akbar',
  'Akshay Kumar',
  'Al Pacino',
  'Albert Einstein',
  'Alia Bhatt',
  'Alka Yagnik',
  'Allu Arjun',
  'Amit Shah',
  'Amitabh Bachchan',
  'Amjad Khan',
  'Amrish Puri',
  'Anand Mahindra',
  'Ananya Panday',
  'Angelina Jolie',
  'Anil Kapoor',
  'Anil Kumble',
  'Anne Hathaway',
  'Anu Malik',
  'Anubhav Singh Bassi',
  'Anupam Kher',
  'Anurag Kashyap',
  'Anushka Sharma',
  'Anushka Shetty',
  'Ariana Grande',
  'Arijit Singh',
  'Arjun Kapoor',
  'Arnold Schwarzenegger',
  'Arshad Warsi',
  'Arun Govil',
  'Arvind Kejriwal',
  'Asha Bhosle',
  'Ashish Chanchlani',
  'Ashoka',
  'Atal Bihari Vajpayee',
  'Atif Aslam',
  'Atlee',
  'Ayushmann Khurrana',
  'B. R. Ambedkar',
  'Baba Ramdev',
  'Babar Azam',
  'Badshah',
  'Bappi Lahiri',
  'Barack Obama',
  'Ben Stokes',
  'Beyoncé',
  'Bhagat Singh',
  'Bharti Singh',
  'Bhaichung Bhutia',
  'Bhuvan Bam',
  'Bill Gates',
  'Billie Eilish',
  'Bipasha Basu',
  'Bob Marley',
  'Bobby Deol',
  'Boman Irani',
  'Brad Pitt',
  'Brett Lee',
  'Brian Lara',
  'Britney Spears',
  'Bruce Lee',
  'Bruce Willis',
  'Bruno Mars',
  'C. V. Raman',
  'CarryMinati',
  'Celine Dion',
  'Charles Darwin',
  'Charlie Chaplin',
  'Chiranjeevi',
  'Chris Evans',
  'Chris Gayle',
  'Chris Hemsworth',
  'Chris Martin',
  'Christopher Nolan',
  'Chunky Panday',
  'Cillian Murphy',
  'Cristiano Ronaldo',
  'Dalai Lama',
  'Daler Mehndi',
  'Daniel Craig',
  'Daniel Radcliffe',
  'Dara Singh',
  'David Beckham',
  'David Warner',
  'Deepika Padukone',
  'Dev Anand',
  'Dhanush',
  'Dharmendra',
  'Dhruv Rathee',
  'Diego Maradona',
  'Diljit Dosanjh',
  'Dimple Kapadia',
  'Disha Patani',
  'Donald Trump',
  'Drake',
  'Droupadi Murmu',
  'Dua Lipa',
  'Dulquer Salmaan',
  'Dwayne Johnson',
  'Ed Sheeran',
  'Ekta Kapoor',
  'Elon Musk',
  'Elvis Presley',
  'Elvish Yadav',
  'Eminem',
  'Emma Stone',
  'Emma Watson',
  'Emraan Hashmi',
  'Enrique Iglesias',
  'Fahadh Faasil',
  'Farah Khan',
  'Farhan Akhtar',
  'Fawad Khan',
  'Freddie Mercury',
  'Gal Gadot',
  'Gautam Adani',
  'Gautam Gambhir',
  'Genelia D’Souza',
  'Glenn Maxwell',
  'Gordon Ramsay',
  'Govinda',
  'Gukesh Dommaraju',
  'Guru Nanak',
  'Guru Randhawa',
  'Hardik Pandya',
  'Harmanpreet Kaur',
  'Harbhajan Singh',
  'Harsh Gujral',
  'Harsha Bhogle',
  'Harshad Mehta',
  'Harry Styles',
  'Hema Malini',
  'Himesh Reshammiya',
  'Hina Khan',
  'Honey Singh',
  'Hrithik Roshan',
  'Hugh Jackman',
  'Imran Khan',
  'Indira Gandhi',
  'Irrfan Khan',
  'Isaac Newton',
  'J. K. Rowling',
  'Jackie Chan',
  'Jackie Shroff',
  'Jagjit Singh',
  'James Cameron',
  'Jasprit Bumrah',
  'Javed Akhtar',
  'Javed Jaffrey',
  'Jaya Bachchan',
  'Jayalalithaa',
  'Jeetendra',
  'Jennifer Aniston',
  'Jennifer Lopez',
  'Joe Biden',
  'John Abraham',
  'John Cena',
  'Johnny Depp',
  'Johnny Lever',
  'Juhi Chawla',
  'Justin Bieber',
  'K. L. Rahul',
  'Kajol',
  'Kailash Kher',
  'Kalpana Chawla',
  'Kamal Haasan',
  'Kangana Ranaut',
  'Kane Williamson',
  'Kapil Dev',
  'Kapil Sharma',
  'Karan Johar',
  'Kareena Kapoor Khan',
  'Karisma Kapoor',
  'Kartik Aaryan',
  'Katrina Kaif',
  'Katy Perry',
  'Keanu Reeves',
  'Kiku Sharda',
  'Kiara Advani',
  'Kim Jong Un',
  'Kim Kardashian',
  'Kiran Bedi',
  'Kishore Kumar',
  'Kriti Sanon',
  'Krushna Abhishek',
  'Kumar Sanu',
  'Kylian Mbappé',
  'Lady Gaga',
  'Lal Bahadur Shastri',
  'Lalu Prasad Yadav',
  'Lasith Malinga',
  'Lata Mangeshkar',
  'Leonardo da Vinci',
  'Leonardo DiCaprio',
  'Lionel Messi',
  'M. S. Dhoni',
  'Madonna',
  'Madhubala',
  'Madhuri Dixit',
  'Mahatma Gandhi',
  'Mahesh Babu',
  'Malaika Arora',
  'Malala Yousafzai',
  'Mamata Banerjee',
  'Mammootty',
  'Mani Ratnam',
  'Manmohan Singh',
  'Manoj Bajpayee',
  'Margot Robbie',
  'Maria Sharapova',
  'Marilyn Monroe',
  'Mark Zuckerberg',
  'Martin Scorsese',
  'Mary Kom',
  'Matt Damon',
  'Michael Jackson',
  'Michael Jordan',
  'Mike Tyson',
  'Miley Cyrus',
  'Milkha Singh',
  'Mithali Raj',
  'Mithun Chakraborty',
  'Mohammed Rafi',
  'Mohammed Shami',
  'Mohanlal',
  'Morgan Freeman',
  'Mother Teresa',
  'MrBeast',
  'Muhammad Ali',
  'Mukesh',
  'Mukesh Ambani',
  'Munawar Faruqui',
  'Muttiah Muralitharan',
  'N. R. Narayana Murthy',
  'Nagarjuna',
  'Nana Patekar',
  'Napoleon',
  'Narendra Modi',
  'Naseeruddin Shah',
  'Nawazuddin Siddiqui',
  'Nayanthara',
  'Neeraj Chopra',
  'Neha Kakkar',
  'Nelson Mandela',
  'Neymar',
  'Nick Jonas',
  'Nicki Minaj',
  'Nirmala Sitharaman',
  'Nita Ambani',
  'Nora Fatehi',
  'Novak Djokovic',
  'Nusrat Fateh Ali Khan',
  'Om Puri',
  'Osama bin Laden',
  'P. T. Usha',
  'P. V. Sindhu',
  'Pankaj Tripathi',
  'Paresh Rawal',
  'Parineeti Chopra',
  'Pat Cummins',
  'Pawan Kalyan',
  'Pelé',
  'Pope Francis',
  'Prabhas',
  'Prajakta Koli',
  'Prakash Raj',
  'Preity Zinta',
  'Priyanka Chopra Jonas',
  'Puneeth Rajkumar',
  'Queen Elizabeth II',
  'Quentin Tarantino',
  'R. D. Burman',
  'R. Madhavan',
  'Rabindranath Tagore',
  'Rafael Nadal',
  'Rahul Dravid',
  'Rahul Gandhi',
  'Raj Kapoor',
  'Rajkumar Hirani',
  'Rajinikanth',
  'Rajiv Gandhi',
  'Rajkummar Rao',
  'Rajpal Yadav',
  'Rajesh Khanna',
  'Rakesh Roshan',
  'Ram Charan',
  'Ranbir Kapoor',
  'Rani Lakshmibai',
  'Rani Mukerji',
  'Ranveer Singh',
  'Rashmika Mandanna',
  'Ratan Tata',
  'Raveena Tandon',
  'Ravi Shastri',
  'Ravichandran Ashwin',
  'Ravindra Jadeja',
  'Rekha',
  'Ricky Ponting',
  'Rihanna',
  'Rishabh Pant',
  'Rishi Kapoor',
  'Riteish Deshmukh',
  'Robert Downey Jr.',
  'Robert Pattinson',
  'Roger Federer',
  'Rohit Sharma',
  'Rohit Shetty',
  'Rowan Atkinson',
  'Rupali Ganguly',
  'Ryan Gosling',
  'Ryan Reynolds',
  'S. Jaishankar',
  'S. P. Balasubrahmanyam',
  'S. S. Rajamouli',
  'Sachin Tendulkar',
  'Sadhguru',
  'Saif Ali Khan',
  'Sai Pallavi',
  'Saina Nehwal',
  'Salman Khan',
  'Samay Raina',
  'Samantha Ruth Prabhu',
  'Sandeep Maheshwari',
  'Sanjay Dutt',
  'Sanjay Leela Bhansali',
  'Sania Mirza',
  'Sara Ali Khan',
  'Sardar Vallabhbhai Patel',
  'Satyajit Ray',
  'Scarlett Johansson',
  'Selena Gomez',
  'Serena Williams',
  'Shaan',
  'Shabana Azmi',
  'Shahid Afridi',
  'Shahid Kapoor',
  'Shah Rukh Khan',
  'Shakti Kapoor',
  'Shakira',
  'Shane Warne',
  'Shankar Mahadevan',
  'Sharmila Tagore',
  'Shashi Kapoor',
  'Shashi Tharoor',
  'Shatrughan Sinha',
  'Shikhar Dhawan',
  'Shilpa Shetty',
  'Shivaji',
  'Shoaib Akhtar',
  'Shreya Ghoshal',
  'Shraddha Kapoor',
  'Shubman Gill',
  'Sidharth Malhotra',
  'Sidhu Moose Wala',
  'Smriti Irani',
  'Smriti Mandhana',
  'Sonakshi Sinha',
  'Sonam Kapoor',
  'Sonu Nigam',
  'Sonu Sood',
  'Sourav Ganguly',
  'Sridevi',
  'Srinivasa Ramanujan',
  'Steve Jobs',
  'Steve Smith',
  'Steven Spielberg',
  'Stephen Hawking',
  'Subhas Chandra Bose',
  'Sunidhi Chauhan',
  'Suniel Shetty',
  'Sunil Chhetri',
  'Sunil Gavaskar',
  'Sunil Grover',
  'Sunny Deol',
  'Sunny Leone',
  'Suriya',
  'Sushant Singh Rajput',
  'Sushmita Sen',
  'Swami Vivekananda',
  'Sylvester Stallone',
  'Tabu',
  'Taapsee Pannu',
  'Tamannaah Bhatia',
  'Tanmay Bhat',
  'Taylor Swift',
  'The Great Khali',
  'The Undertaker',
  'The Weeknd',
  'Tiger Shroff',
  'Tiger Woods',
  'Tipu Sultan',
  'Tom Cruise',
  'Tom Hanks',
  'Tom Holland',
  'Udit Narayan',
  'Usain Bolt',
  'Varun Dhawan',
  'Vicky Kaushal',
  'Vidya Balan',
  'Vijay',
  'Vijay Deverakonda',
  'Vijay Sethupathi',
  'Vin Diesel',
  'Vinod Khanna',
  'Vir Das',
  'Virat Kohli',
  'Viswanathan Anand',
  'Vladimir Putin',
  'Wasim Akram',
  'Will Smith',
  'William Shakespeare',
  'Winston Churchill',
  'Yash',
  'Yash Chopra',
  'Yogi Adityanath',
  'Yuvraj Singh',
  'Zakir Khan',
  'Zeenat Aman',
  'Zendaya',
  'Zoya Akhtar',
].sort((a, b) => a.localeCompare(b, 'en-IN', { sensitivity: 'base' }))

export const WIKIPEDIA_TITLE_OVERRIDES: Record<string, string> = {
  'Amjad Khan': 'Amjad Khan (actor)',
  Atlee: 'Atlee (director)',
  'Baba Ramdev': 'Ramdev',
  Badshah: 'Badshah (rapper)',
  'Chris Evans': 'Chris Evans (actor)',
  'David Warner': 'David Warner (cricketer)',
  Drake: 'Drake (musician)',
  'Genelia D’Souza': "Genelia D'Souza",
  'M. S. Dhoni': 'MS Dhoni',
  Mukesh: 'Mukesh (singer)',
  'P. T. Usha': 'PT Usha',
  'Sardar Vallabhbhai Patel': 'Vallabhbhai Patel',
  Shaan: 'Shaan (singer)',
  'Steve Smith': 'Steve Smith (cricketer)',
  Tabu: 'Tabu (actress)',
  Vijay: 'Vijay (actor)',
  Yash: 'Yash (actor)',
  'Zakir Khan': 'Zakir Khan (comedian)',
}
